title = 'Example configuration.'  # Some kind of introduction

[bot]  # I'd say the main config data.
exts = [
    'jishaku',
    'cogs.owner',
    'cogs.events',
    'cogs.errors',
    'cogs.useful',
    'cogs.fun',
    'cogs.images',
    'cogs.moderation',
    'cogs.misc',
    'cogs.help',
    'cogs.top'
]
version = 'the bot version'
token = 'my beautiful token here.'

[database]  # these are credits you log in to the asyncpg pool with.
user = ''
password = ''
host = ''
database = ''

[ipc]  # ipc server credits.
host = ''
port = 8765
secret_key = ''

[API]  # you can insert APIs' URLs here
sr_api = 'some-random-api.ml'