title = 'Boribay bot configuration.'  # Some kind of introduction

[bot]  # I'd say the main config data.
exts = [
    'this is the list of extensions',
    'example below',
    'cogs.owner'
]
version = 'the bot version'
description = 'the bot description that i want'
token = 'my beautiful token here.'

[database]  # these are credits you log in to the asyncpg pool with.
user = ''
password = ''
host = ''
database = ''

[ipc]  # ipc server credits.
host = ''
port = 8765
secret_key = ''

[API]  # you can insert APIs' URLs here
apis = [
    'some-random-api.ml'
]

[mongo]  # MongoDB credits that I use to keep todos cluster working.
username = ''
password = ''
project = ''
database = ''

[music]  # Lavalink/Wavelink nodes to add the music support.
host = ''
port = 2333
rest_uri = ''
password = ''
identifier = ''
region = ''