title = 'Boribay bot configuration.'

[bot]  # The bot configuration.
exts = [  # I had to hardcode extensions, sorry for that...
    'jishaku',
    'boribay.cogs.owner',
    'boribay.cogs.admin',
    'boribay.cogs.events',
    'boribay.cogs.errors',
    'boribay.cogs.useful',
    'boribay.cogs.fun',
    'boribay.cogs.ipc',
    'boribay.cogs.images',
    'boribay.cogs.moderation',
    'boribay.cogs.misc',
    'boribay.cogs.help',
    'boribay.cogs.users',
    'boribay.cogs.config'
]
beta = false
news_channel = 'Replace with a channel ID where you would type announcements about the bot updates.'
errors_channel = 'Replace with a channel ID where you would like to log errors in.'
owner_exts = ['Jishaku', 'Events', 'Owner', 'ErrorHandler']  # Extensions that have to be ignored.
version = '1.1.3'  # The bot version.
token = 'Put your token here.'
dbl_token = 'Your TopGG API token here.'

[database]  # Database credentials to be able to log with.
user = 'postgres'  # But I'm sure you have a different username
password = 'youshallnotpass!!'
host = 'localhost'
database = 'Boribay'  # More likely to create a database with that name.

[ipc]  # IPC server credentials.
host = 'localhost'
port = 8765
secret_key = 'Put your secret key here.'

[links]  # All links you need to use.
log_url = 'Your webhook URL to log guilds.'
invite_url = 'https://discord.com/api/oauth2/authorize?client_id=735397931355471893&permissions=8&scope=bot'
github_url = 'https://github.com/Dositan/Boribay/'
support_url = 'https://discord.gg/B4k8tmPDbz/'
topgg_url = 'https://top.gg/bot/735397931355471893#/'

[API]  # Array variables mean that the token must be the second element there.
# Looks like I'm such in a good mood to leak all the API URL's I've been using :^)
anime = 'https://kitsu.io/api/edge'
ud = 'http://api.urbandictionary.com/v0/define'
qr = 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data='
trivia = 'https://opentdb.com/api.php?amount=1'
screenshot = 'https://image.thum.io/get/width/1920/crop/675/maxAge/1/noanimate/'
quote = 'https://api.quotable.io/random'
caption = 'https://captionbot.azurewebsites.net/api/messages'
covid = 'https://disease.sh/v3/covid-19/'

# API's that require a token ↓
google_key = 'Put your Google Developer key here.'
weather = ['http://api.openweathermap.org/data/2.5/weather?', 'Token of this API.']
dagpi = ['https://beta.dagpi.xyz/image/', 'Token of this API.']
alex = ['https://api.alexflipnote.dev/', 'Token of this API.']
